version: 0.2
env:
  secrets-manager:
    DOCKER_CREDENTIALS: "arn:aws:secretsmanager:us-east-1:775211670190:secret:docker-credentials"     
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d9y2l7x4
      - REPOSITORY_URI=public.ecr.aws/d9y2l7x4/ecr-springboot
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')      
  build:
    commands:
      - echo "Logging in to Docker..."
      - DOCKER_USERNAME=$(echo $DOCKER_CREDENTIALS | jq -r '.DOCKERHUB_USERNAME')
      - DOCKER_PASSWORD=$(echo $DOCKER_CREDENTIALS | jq -r '.DOCKERHUB_PASSWORD')
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      # Define container name and create imagedefinitions.json for ECS
      - DOCKER_CONTAINER_NAME=springboot
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo Displaying imagedefinitions.json content
      - cat imagedefinitions.json
